### ISSUE TITLE
How to guide: User groups

### ISSUE THREAD

**Issue by Parth7223** [avniproject/avni-documentation#12]
### Need:
Would help to delegate some of the simple work to the admin client users.

### AC:
- The readme is for end users/clients/analysts
- Address the comments [Documentation link](https://docs.google.com/document/d/1hEX5feHhKvCSP26X-_ibuZKSvc8VI_Bq/edit?rtpof=true)
- Improvise any if possible
- Adhere to [readme guidelines](https://avni.readme.io/docs/readme-guidelines) wherever applicable
- Move it to code review ready
- the doc can be published under END USER GUIDE once moved to the lane Further Action Required

**Comment by mahalakshme** [comment]
@Parth7223 have added some comments

**Comment by mahalakshme** [comment]
@1t5j0y updated the lane to publish it

**Comment by 1t5j0y** [comment]
https://avni.readme.io/docs/user-groups
