### ISSUE TITLE
[Documentation] Dashboard and Report cards - after 10.0

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/avni-documentation#17]
### AC:
- Add about what each standard report card does and how they work with filters. 
- Add about how to configure filters at report card level and how does it help
- Add about what filters are not compatible with certain report cards
- Also add some suggestions to follow to create more intuitive dashboards. Eg: Having a subject type filter at report card level and dashboard level doesn't make much sense, and user will be confused.
- Try to integrate the above with the documentation already present and not duplicate or replace the existing one. 
- Add under the implementors guide
- Anything that I have missed above.

### Need:
Clients do like to know what are these numbers on default dashboard. Hence adding documentation explaining about each number is helpful.

### AC:
- The readme is for end users/clients/analysts
- Address the comments [here](https://docs.google.com/document/d/1l4LrE5okZoV0GJdlF92URGszIYYasbSedEVHKGkmBOc/edit)
- Improvise any if possible
- Adhere to [readme guidelines](https://avni.readme.io/docs/readme-guidelines) wherever applicable
- Move it to code review ready
- the doc can be published under END USER GUIDE once moved to the lane Further Action Required

**Comment by pkundu** [comment]
@kameshbhariya can you pick this once the SR app analysis is completed

**Comment by mahalakshme** [comment]
@1t5j0y moving this card back to Ready and will update the AC inline with 10.0 release

**Comment by 1t5j0y** [comment]
Updated https://avni.readme.io/docs/offline-reports
