### ISSUE TITLE
How to guide: Creating catchments and users via Avni Admin Console

### ISSUE THREAD

**Issue by pkundu** [avniproject/avni-documentation#27]
### AC:
- The readme is for end users/clients/analysts
- Address the comments [here](https://docs.google.com/document/d/1FjGoiuALmPi6Pj8miFpzwNWoyBR0D8wAUfGBViefLo0/edit) 
- Improvise any if possible
- Adhere to [readme guidelines](https://avni.readme.io/docs/readme-guidelines) wherever applicable
- Move it to code review ready
- the doc can be published under END USER GUIDE once moved to the lane Further Action Required

**Comment by mahalakshme** [comment]
@1t5j0y updated the lane to publish it

**Comment by 1t5j0y** [comment]
https://avni.readme.io/docs/users-and-catchments
