### ISSUE TITLE
{Documentation}: How to guide: Adding locations

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/avni-documentation#3]
### Need:
New CSV upload enhancement release will take more than a month from now. Analysts and end users are facing issues in the mean time to figure out how to do the same and with trial and error approach which ends up consuming more of their time. So documentation for existing Location upload need to be added. Also there are things not related to the enhancements in CSV upload.

### AC:
- The readme is for end users/clients/analysts
- Address the comments [here](https://docs.google.com/document/d/1qxeGA9wyn6HUpKl1WjnxYghZBhVgVCVAP_AITxJBY_M/edit?usp=sharing) - commented only on fundamental issues since CSV enhancements will soon be released
- Improvise any basic things if possible
- Adhere to [readme guidelines](https://avni.readme.io/docs/readme-guidelines) wherever applicable - if it will take more time ignore
- Move it to code review ready
- the doc can be published under `END USER GUIDE` under a new section called `Data upload` once moved to the lane `Further Action Required`

**Comment by himeshr** [comment]
@mahalakshme Please review https://docs.google.com/document/d/1qxeGA9wyn6HUpKl1WjnxYghZBhVgVCVAP_AITxJBY_M/edit?usp=sharing

**Comment by mahalakshme** [comment]
@pkundu Product developer has created the new documentation. I have further added some comments and edited few things. So let me know if implementation team can take up from here
