### ISSUE TITLE
[Documentation] Creating locations - after 10.0

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-documentation#30]
### AC:
- Add about creating locations via CSV and web app
- Mention the nuances like being able to update the parent of a location
- about different modes - Edit, Create
- Regarding different location hierarchies
- Location properties and how to set them
- Once done add it under 'End User Guide' in readme.
- Also merge the contents with any already available to avoid duplicates, or replace it.

Ensure that you retain all the relevant information from the previous version of Locations Upload document, that is present [here](https://docs.google.com/document/d/1qxeGA9wyn6HUpKl1WjnxYghZBhVgVCVAP_AITxJBY_M/edit#heading=h.2akq80588qau)
A draft document for this is available [here](https://docs.google.com/document/d/1SL6KJgetf35RyKBwn9LgGxBfvyT2vk-FuoHMTkUrUgQ/edit?usp=sharing)

**Comment by himeshr** [comment]
https://avni.readme.io/docs/how-to-guide-setting-up-locations-via-csv-upload

**Comment by mahalakshme** [comment]
@himeshr I suggest removing the below:
-  These Forms are made up of the same building blocks of FormElementGroups and FormElements like Forms of other types. (Since users know only questions and pages)
-  The word 'dynamic' before form and location properties or properties since they are not dynamic. We also don't 've a easy way to update them other than via CSV. And they are mostly constants like block code, state code, high risk location etc., which will not change for years.

Would 've been good if same example of location hierarchy has been used to explain the entire documentation. But this is for remembering next time. No need to update now since this will involve more work. But overall looks comprehensive and clear.

**Comment by himeshr** [comment]
> * These Forms are made up of the same building blocks of FormElementGroups and FormElements like Forms of other types.

Made changes as follows:
- Replaced "FormElementGroups" with Page and FormElement with Question
- Replaced Dynamic word with other appropriate adjectives like other, additional, etc..
